import type { Room, Booking, Guest } from "@/types";

export const mockRooms: Room[] = [
  {
    id: "1",
    name: "Quarto 101 - Vista Castelo",
    room_number: "101",
    floor: 1,
    room_type: "Standard",
    base_price: 80,
    max_guests: 1,
    amenities: ["Wi-Fi", "Ar Condicionado", "Varanda"],
    images: ["/room-1.jpg"],
    is_available: true,
    rental_type: "nightly",
    minimum_nights: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Quarto 102 - Vista Jardim",
    room_number: "102",
    floor: 1,
    room_type: "Standard",
    base_price: 75,
    max_guests: 1,
    amenities: ["Wi-Fi", "TV"],
    images: ["/room-2.jpg"],
    is_available: true,
    rental_type: "nightly",
    minimum_nights: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Suite 201 - Premium",
    room_number: "201",
    floor: 2,
    room_type: "Suite",
    base_price: 120,
    max_guests: 1,
    amenities: ["Wi-Fi", "Ar Condicionado", "Cozinha", "Jacuzzi"],
    images: ["/room-3.jpg"],
    is_available: true,
    rental_type: "nightly",
    minimum_nights: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Suite 202 - Deluxe",
    room_number: "202",
    floor: 2,
    room_type: "Suite",
    base_price: 110,
    max_guests: 1,
    amenities: ["Wi-Fi", "Ar Condicionado", "Mini-bar"],
    images: ["/room-4.jpg"],
    is_available: true,
    rental_type: "nightly",
    minimum_nights: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Studio 301 - Arroios",
    room_number: "301",
    floor: 3,
    room_type: "Large",
    base_price: 90,
    max_guests: 1,
    amenities: ["Wi-Fi", "Cozinha", "Máquina de Lavar"],
    images: ["/room-5.jpg"],
    is_available: true,
    rental_type: "biweekly",
    minimum_nights: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockBookings: Booking[] = [];

export const mockGuests: Guest[] = [];

export const mockProperty = {
  id: "default-property-id",
  name: "Gestão Arroios",
  address: "Rua de Arroios",
  city: "Lisboa",
  country: "Portugal",
  contactEmail: "info@gestaoarroios.pt",
  contactPhone: "+351 210 000 000",
  checkInTime: "15:00",
  checkOutTime: "11:00",
  currency: "EUR",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
