// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxkjkeygfzzgazrwsnki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4a2prZXlnZnp6Z2F6cndzbmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczMDc5NDAsImV4cCI6MjA4Mjg4Mzk0MH0.HWBvyiFm6TcvTVP7WLuugrAxGcm5Kh7qUYwrgGX65nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
